variables:
  TF_CLI_ARGS_init: "-lockfile=readonly"
  TF_VAR_pve_api_url: ${PVE_API_URL}
  TF_VAR_pve_user: ${PVE_USER}
  TF_VAR_pve_password: ${PVE_PASSWORD}
  TSFILE: "tailscale_1.28.0_amd64.tgz"

include:
  - component: $CI_SERVER_FQDN/components/opentofu/validate-plan-apply@0.21.0
    inputs:
      version: 0.21.0
      opentofu_version: 1.7.1
      root_dir: homelab/opentofu/proxmoxve/trinity-helios
      state_name: latest_trinity_helios_pve
      auto_apply: true

stages: [validate, test, build, deploy]

plan:
  before_script:
    - apk add --no-cache tailscale jq curl iptables ip6tables bind-tools
    - tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
    - tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname="gitlab-ci-${CI_JOB_ID}" --accept-dns --accept-routes
    - tailscale status
    - cat /etc/resolv.conf > /tmp/resolv.conf.backup
    - echo "nameserver 100.100.100.100" > /etc/resolv.conf
    - cat /tmp/resolv.conf.backup >> /etc/resolv.conf
    - cat /etc/resolv.conf
